baseURL = "https://linuxbozo.github.io/"
languageCode = "en-us"
title = "M. Adam Kendall"
theme = "m10c"

[params]
  description = "maker + coder + devops + beer + bourbon - bullshit."
  author = "M. Adam Kendall"
  menu_item_separator = " ▪︎ "
  [params.style]
    darkestColor = "#ECEFF4"
    darkColor = "#D8DEE9"
    lightColor = "#81A1C1"
    lightestColor = "#5E81AC"
    primaryColor = "#EBCB8B"
  [[params.social]]
    name = "github"
    url = "https://github.com/linuxbozo"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/linuxbozo"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
