baseURL = "https://linuxbozo.github.io/"
languageCode = "en-us"
title = "wtf, linuxbozo"
theme = "m10c"

enableGitInfo = true
enableRobotsTXT = true

[permalinks]
  posts = "/:year/:month/:slug/"

[params]
  description = "maker + coder + devops + beer + bourbon - bullshit."
  author = "M. Adam Kendall"
  GitHubUser = "LinuxBozo"
  menu_item_separator = " ▪︎ "
  [params.style]
    darkestColor = "#2E3440"
    darkColor = "#3B4252"
    lightColor = "#bbcad9"
    lightestColor = "#A3BE8C"
    primaryColor = "#88C0D0"
  [[params.social]]
    name = "github"
    url = "https://github.com/linuxbozo"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/linuxbozo"
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/linuxbozo"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
